# Generated by Django 6.0.4 on 2026-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsgAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('original_text', models.TextField()),
                ('result_json', models.JSONField()),
                ('verdict', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ESG Analysis',
                'verbose_name_plural': 'ESG Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
